export const SET_USER_TOKEN = 'SET_USER_TOKEN'
export const SET_CURRENT_PAGE = 'SET_CURRENT_PAGE'
export const SET_EVENT_LOADING = 'SET_EVENT_LOADING'
export const SET_OPEN_SIGN_UP_SHEET = 'SET_OPEN_SIGN_UP_SHEET'

